### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by rishissahu** [aryanargupta/HackTheHackerrank#11]
CONTRIBUTING.md need some improvement.

**Comment by aryanargupta** [comment]
Can you specify?

**Comment by rishissahu** [comment]
Contributing.md does not include the proper instruction how to contribute.
I have edited the file and added step by step instructions how to create new PR.

**Comment by aryanargupta** [comment]
> Contributing.md does not include the proper instruction how to contribute. I have edited the file and added step by step instructions how to create new PR.

Ok GFI, will see what changes you suggest

**Comment by rishissahu** [comment]
This issue is resolved.
