### ISSUE TITLE
Super Reduced String

### ISSUE THREAD

**Issue by rishissahu** [aryanargupta/HackTheHackerrank#4]
Reduce a string of lowercase characters in range ascii[‘a’..’z’]by doing a series of operations. In each operation, select a pair of adjacent letters that match, and delete them.

Delete as many characters as possible using this method and return the resulting string. If the final string is empty, return Empty String

**Comment by aryanargupta** [comment]
Note, that whenever raising an issue in future, wait for the maintainer(s) to assign the issue, and then only send the PR. As of now, GFI.

**Comment by rishissahu** [comment]
Okay.
