### ISSUE TITLE
Currency Formatter

### ISSUE THREAD

**Issue by rishissahu** [aryanargupta/HackTheHackerrank#6]
Given a number, payment, denoting an amount of money, use the getCurrencyInstance method to convert  into the US, Indian, Chinese, and French currency formats. Then print the formatted values as follows:

US: formattedPayment
India: formattedPayment
China: formattedPayment
France: formattedPayment

Source link: https://www.hackerrank.com/challenges/java-currency-formatter/problem

**Comment by rishissahu** [comment]
I would like to share my code of this problem.

**Comment by aryanargupta** [comment]
GFI  @rishissahu 👍 Also, go through the Contributing.md once more to create the optimal PR.
